name: RDP with Tailscale VPN and Codespace

on:
  workflow_dispatch:

jobs:
  start-rdp-codespace:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 ore
    steps:
      - name: Generate random RDP password
        id: gen-pass
        run: |
          PASS=$(openssl rand -base64 12)
          echo "password=$PASS" >> $GITHUB_OUTPUT

      - name: Get repository id
        id: repo-id
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.repo.id;

      - name: Create GitHub Codespace
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.rest.codespaces.createForAuthenticatedUser({
              repository_id: parseInt('${{ steps.repo-id.outputs.result }}'),
              branch: 'main',
              machine: 'standard-large', // Ajustează după disponibilitate
              location: 'East US'
            });
            console.log('Codespace creat:', response.data);
            return response.data;

      - name: Connect to Tailscale with auth key
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: latest
          use-cache: 'true'

      - name: Show Tailscale IP
        id: show-ip
        run: |
          IP=$(tailscale ip -4)
          echo "tailscale_ip=$IP" >> $GITHUB_OUTPUT
          echo "IP Tailscale: $IP"

      - name: Show RDP credentials
        run: |
          echo "RDP IP (prin Tailscale): ${{ steps.show-ip.outputs.tailscale_ip }}"
          echo "RDP parola generata: ${{ steps.gen-pass.outputs.password }}"

      - name: Keep session alive 6 hours
        run: sleep 21600

      - name: Cleanup (opțional)
        run: echo "Cleanup steps here"
